; Please do not edit this file! If this file is modified, results are unpredictable.
; Instead of modifying this file, simply create a new MEGA Analysis Options file by using MEGA.
[ MEGAinfo ]
ver                              = 10200331-x86_64 MS Windows      
[ DataSettings ]
datatype                         = snNucleotide                    
containsCodingNuc                = False                           
MissingBaseSymbol                = ?                               
IdenticalBaseSymbol              = .                               
GapSymbol                        = -                               
Labelled Sites                   = All Sites                       
Labels to Include                =                                 
[ ProcessTypes ]
ppAncSeq                         = true                            
ppMP                             = true                            
[ AnalysisSettings ]
Analysis                         = Ancestral Sequence Inference    
Tree to Use                      = Use tree from file              
Max Relative Rate Ratio          = 20                              
Statistical Method               = Maximum Parsimony               
Substitution Model               = ====================            
Substitutions Type               = Nucleotide                      
Data Subset to Use               = ====================            
Gaps/Missing Data Treatment      = Use all sites                   
Site Coverage Cutoff (%)         = Not Applicable                  
Has Time Limit                   = False                           
Maximum Execution Time           = -1                              
